"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import pet as components_pet
from typing import Optional


@dataclasses.dataclass
class DeletePetRequest:
    pet_id: int = dataclasses.field(metadata={'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': False }})
    r"""Pet id to delete"""
    api_key: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'api_key', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class DeletePetResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    pet: Optional[components_pet.Pet] = dataclasses.field(default=None)
    r"""Pet deleted"""
    

