"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import pet as components_pet
from enum import Enum
from typing import List, Optional

class Status(str, Enum):
    r"""Status values that need to be considered for filter"""
    AVAILABLE = 'available'
    PENDING = 'pending'
    SOLD = 'sold'


@dataclasses.dataclass
class FindPetsByStatusRequest:
    status: Optional[Status] = dataclasses.field(default=Status.AVAILABLE, metadata={'query_param': { 'field_name': 'status', 'style': 'form', 'explode': True }})
    r"""Status values that need to be considered for filter"""
    



@dataclasses.dataclass
class FindPetsByStatusResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    pets: Optional[List[components_pet.Pet]] = dataclasses.field(default=None)
    r"""successful operation"""
    

