"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import user as components_user
from typing import Optional


@dataclasses.dataclass
class GetUserByNameRequest:
    username: str = dataclasses.field(metadata={'path_param': { 'field_name': 'username', 'style': 'simple', 'explode': False }})
    r"""The name that needs to be fetched. Use user1 for testing."""
    



@dataclasses.dataclass
class GetUserByNameResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    user: Optional[components_user.User] = dataclasses.field(default=None)
    r"""successful operation"""
    

