"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import apiresponse as components_apiresponse
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class UploadFileRequest:
    pet_id: int = dataclasses.field(metadata={'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': False }})
    r"""ID of pet to update"""
    additional_metadata: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'additionalMetadata', 'style': 'form', 'explode': True }})
    r"""Additional Metadata"""
    request_body: Optional[bytes] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/octet-stream' }})
    



@dataclasses.dataclass
class UploadFileResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    api_response: Optional[components_apiresponse.APIResponse] = dataclasses.field(default=None)
    r"""successful operation"""
    

