workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    sample-source:
        inputs:
            - location: openapi.yaml
targets:
    python-package:
        target: python
        source: sample-source
        publish:
            pypi:
                token: $pypi_token
